//API:1
//Scenario 1 => Returns a list of all todos whose status is 'TO DO'
//Sample API /todos/?status=TO%20DO
###
GET http://localhost:3000/todos/?status=TO%20DO

//Scenario 2 => Returns a list of all todos whose priority is 'HIGH'
//Sample API /todos/?priority=HIGH
###
GET http://localhost:3000/todos/?priority=HIGH

//Scenario 3 => Returns a list of all todos whose priority is 'HIGH' and status is 'IN PROGRESS'
//Sample API /todos/?priority=HIGH&status=IN%20PROGRESS
###
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

//API:2 => Returns a specific todo based on the todo ID
//Path: /todos/:todoId/
###
GET http://localhost:3000/todos/1/

//API:3 => Create a todo in the todo table,
//Path: /todos/
###
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

//API:4 => Updates the details of a specific todo based on the todo ID
//Path: /todos/:todoId/
//Scenario 1 => { "status": "DONE" }
###
PUT http://localhost:3000/todos/5/
Content-Type: application/json

{ "status": "DONE" }

//Scenario 2 => { "priority": "HIGH" }
###
PUT http://localhost:3000/todos/4/
Content-Type: application/json

{ "priority": "HIGH" }

//Scenario 3 => { "todo": "Some task" }
###
PUT http://localhost:3000/todos/4/
Content-Type: application/json

{ "todo": "Some task" }

//API:5 Deletes a todo from the todo table based on the todo ID
//Path: /todos/:todoId/
###
DELETE http://localhost:3000/todos/5/